{"description":"Like any R objects, errors captured with catchers like tryCatch()\nhave a class() which you can test with inherits().  However,\nwith chained errors, the class of a captured error might be\ndifferent than the error that was originally signalled. Use\ncnd_inherits() to detect whether an error or any of its parent\ninherits from a class.\n","example_call":"cnd_inherits(cnd, class)"}